---
  version: '3'
  
  volumes:
    wordpress:
    db:
  
  services:
    reverse-proxy-nginx:
      container_name: nginx
      build: 
        context: .
      ports: 
        - "80:80"
  
    wordpress:
      container_name: wordpress
      image: wordpress:5.7.2-apache
      environment:
        - WORDPRESS_DB_USER=root
        - WORDPRESS_DB_PASSWORD=wordpress
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_NAME=wordpressdb
      depends_on:
        - db
      volumes:
        - "wordpress:/var/www/html"
      
    db:
      container_name: db
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=wordpress
        - MYSQL_DATABASE=wordpressdb
      volumes:
        - "db:/var/lib/mysql"
  