apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-c
  labels:
    app: deployment-c
spec:
  selector:
    matchLabels:
      app: deployment-c
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-c
    spec:
      containers:
        - name: devopsacademyc
          image: eficodeacademy/devopsacademyc:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
            - name: KEY
              valueFrom:
                configMapKeyRef:
                  name: deployment-c-configmap
                  key: KEY
