apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  labels:
    app: deployment-b
spec:
  selector:
    matchLabels:
      app: deployment-b
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-b
    spec:
      containers:
      - name: devopsacademyb
        image: eficodeacademy/devopsacademyb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000