apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: deployment-c
spec:
  type: ClusterIP
  selector:
    app: deployment-c
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000