apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: deployment-a
spec:
  type: NodePort
  selector:
    app: deployment-a
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000