apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: deployment-b
spec:
  type: ClusterIP
  selector:
    app: deployment-b
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000